#%RAML 1.0 NamedExample
  {
          "userID": "1",
          "firstName": "Betty",
          "lastname": "Tilahun",
          "email": "bettyTil@gmail.com",
          "address":
          {
            "city": "Addis Ababa",
            "state": "Addis Ababa" ,
            "country": "Ethiopia"
          }
           
 }