#%RAML 1.0 NamedExample
  [
          {
          "userID": "1",
          "firstName": "Betty",
          "lastname": "Tilahun",
          "email": "bettyTil@gmail.com",
          "address":
          {
            "city": "Addis Ababa",
            "state": "Addis Ababa" ,
            "country": "Ethiopia"
          }
           
        }, 
        {
          "userID": "2",
          "firstName": "Rebecca",
          "lastname": "Yilma",
          "email": "rebeccayilma@gmail.com",
          "address":
          {
            "city": "Addis Ababa",
            "state": "Addis Ababa" ,
            "country": "Ethiopia"
          }
           
        }
        
        ]